### ISSUE TITLE
在el-drawer中打开组件的设置dialog时，遮罩层问题

### ISSUE THREAD

**Issue by Huzhangjie** [giscafer/vue-json-schema-editor-visual#5]
在el-drawer中使用了<json-schema-editor> 组件，高级设置时，打开弹窗。遮罩层会覆盖弹窗内容。
![dialog-bug](https://user-images.githubusercontent.com/29808480/112830091-a6b80680-90c4-11eb-8e23-a63eff83a370.png)

**Comment by giscafer** [comment]
demo 好像没有这个问题。http://blog.giscafer.com/vue-json-schema-editor-visual/

**Comment by Huzhangjie** [comment]
嗯嗯，因为demo中是直接使用的组件，我是在el-drawer 中使用了组件。就相当于有一个嵌套弹窗的问题。Element官方文档上也是说有嵌套弹窗就需要设置 `append-to-body: true` 来着。问题不大
